# Site settings
title: "Antoine Fossey"
description: "Antoine Fossey's resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Antoine Fossey"
resume_title:                   "Freelance Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "fossey.antoine@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "Lyon"

resume_header_contact_info:     "Lyon, France • fossey.antoine@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Hi! I'm a freelance software engineer living in Lyon.</br>I specialize myself in Java webservices development but I also did quite a lot of Javascript with Angular and a bit of React.</br>My current interests are in functional and reactive programming, I like the logic and the readability of the code they tend to produce.</p>"


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message, 
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  #resume_github_url:            "https://github.com/afossey"
  resume_twitter_url:           "http://twitter.com/afossey"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/antoinefossey"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://afossey.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
